language: node_js
node_js:
  - "node"
  - "8"
  - "6"

addons:
  code_climate:
    repo_token: b4ef7769e0f8f04456e8e1168b4beb44561bd5ce9ca216458a164e19c4cf7308

branches:
  only:
    - master

cache: yarn

install:
  - yarn
  - npm run lint
  - npm run test

script:
  - npm run build

after_success:
  - npm run travis-deploy-once "npm run codeclimate && npm run semantic-release"

notifications:
  email: false
