environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --ignore-engines

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn test

build: off
